name: peer-backend CI pipeline

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependecies
        run: yarn install
      - name: Lint the code
        run: yarn lint
      - name: Test the code
        run: yarn test
      - name: Run E2E tests
        run: yarn test:e2e
